FROM golang:1.23-alpine AS builder
WORKDIR /app

COPY go.work* ./
COPY go.mod go.sum ./
COPY gateway/ ./gateway/
COPY services/ ./services/

WORKDIR /app/gateway
RUN go mod download

WORKDIR /app
RUN go build -o api-gateway ./gateway/

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/api-gateway .
EXPOSE 8080
CMD ["./api-gateway"]