apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  USER_SERVICE_URL: "http://user-service:8081"
  ORDER_SERVICE_URL: "http://order-service:8082"
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque
stringData:
  JWT_SECRET: "super-secret-key"